steps:
# Rebase to target branch for every PR. This means users don't have to
# rebase every time target branch changes. As long as the PR applies cleanly, we
# will validate it.
- bash: |
    git config user.email 'info@openttd.org'
    git config user.name 'OpenTTD CI'
    git rebase origin/$SYSTEM_PULLREQUEST_TARGETBRANCH
  displayName: 'Rebase to $(System.PullRequest.TargetBranch)'
